openapi: 3.0.0
info:
  version: 0.1.1
  title: Nikah Time
  license:
    name: MIT
servers:
  - url: /api/
paths:
  /login:
    post:
      summary: Вход пользователя
      operationId: login
      tags:
        - Login
      requestBody:
        description: Данные для авторизации
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth'
            examples:
              Email:
                value:
                  grantType: "email"
                  email: "test@gmail.com"
                  password: "ne6Jo$zi"
              PhoneNumber:
                value:
                  grantType: "phoneNumber"
                  phoneNumber: "+74951239999"
                  password: "LRn&z!4Y"
              GoogleIdToken:
                value:
                  grantType: "googleIdToken"
                  idToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjFiZjhhODRkM2VjZDc3ZTlmMmFkNWYwNmZmZDI2MDcwMWRkMDZkOTAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIzMjExNzk3NzU4MDctZWpmY2UzZDU5aWUwN2hnc2VnMzB2NWE3OGg4dGlrMTcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIzMjExNzk3NzU4MDctaXYyaTVvZXEwZjRkanRlYmplNGZmbW5obXBmZmpzOWUuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTEwNTk2ODk5NTc3MDgwNDg1MjMiLCJlbWFpbCI6ImRlaWdoZDA4QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoi0JTQvNC40YLRgNC40Lkg0JfQsNC50YbQtdCyIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBVFhBSnhKcXNJaWVmYXdpZHFKQ3N1Sl9kSy1Pa2RZWTFPa3VybTFWNy1hPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6ItCU0LzQuNGC0YDQuNC5IiwiZmFtaWx5X25hbWUiOiLQl9Cw0LnRhtC10LIiLCJsb2NhbGUiOiJydSIsImlhdCI6MTYyNTY2Nzk5NCwiZXhwIjoxNjI1NjcxNTk0fQ.gbb5A30-Oqiu_o5bKrov4Sjm5I-7p0VCFxqMWaPfV-5wHBCVs3PR70pOxfLeyqqJHZkauE_KheKWxgOMo6CN4VhjPeOYWzmVH88fVB1ZWThfCkTD06rxWKsfY8I0__kNocP3K-iT5Az908lMtEfl9QQOJfCvgezxi-TKlBRP8R44s9s9bsMMvli08g_J2YEb5jZm6OH2W7KFTeoLzM3okcDEfnX5m--Qx52x6R9LqBPxD0AvzdenZwchQ3yNzpfLxG2tXpN8wehGijlJ-tG4vxSyC8IKy7x09k5whGWMTx_ssIDLQlnAjW91JibhKvgSZnWvyNmFnWey_D6gdSF8ig"
      responses:
        '200':
          description: Данные аккаунта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /registration:
    post:
      summary: Регистрация пользователя
      operationId: registration
      tags:
        - Registration
      requestBody:
        description: Данные для авторизации
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth'
            examples:
              Email:
                value:
                  grantType: "email"
                  email: "test@gmail.com"
                  password: "ne6Jo$zi"
              PhoneNumber:
                value:
                  grantType: "phoneNumber"
                  phoneNumber: "+74951239999"
                  password: "LRn&z!4Y"
              GoogleIdToken:
                value:
                  grantType: "googleIdToken"
                  idToken: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjFiZjhhODRkM2VjZDc3ZTlmMmFkNWYwNmZmZDI2MDcwMWRkMDZkOTAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIzMjExNzk3NzU4MDctZWpmY2UzZDU5aWUwN2hnc2VnMzB2NWE3OGg4dGlrMTcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIzMjExNzk3NzU4MDctaXYyaTVvZXEwZjRkanRlYmplNGZmbW5obXBmZmpzOWUuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTEwNTk2ODk5NTc3MDgwNDg1MjMiLCJlbWFpbCI6ImRlaWdoZDA4QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoi0JTQvNC40YLRgNC40Lkg0JfQsNC50YbQtdCyIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBVFhBSnhKcXNJaWVmYXdpZHFKQ3N1Sl9kSy1Pa2RZWTFPa3VybTFWNy1hPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6ItCU0LzQuNGC0YDQuNC5IiwiZmFtaWx5X25hbWUiOiLQl9Cw0LnRhtC10LIiLCJsb2NhbGUiOiJydSIsImlhdCI6MTYyNTY2Nzk5NCwiZXhwIjoxNjI1NjcxNTk0fQ.gbb5A30-Oqiu_o5bKrov4Sjm5I-7p0VCFxqMWaPfV-5wHBCVs3PR70pOxfLeyqqJHZkauE_KheKWxgOMo6CN4VhjPeOYWzmVH88fVB1ZWThfCkTD06rxWKsfY8I0__kNocP3K-iT5Az908lMtEfl9QQOJfCvgezxi-TKlBRP8R44s9s9bsMMvli08g_J2YEb5jZm6OH2W7KFTeoLzM3okcDEfnX5m--Qx52x6R9LqBPxD0AvzdenZwchQ3yNzpfLxG2tXpN8wehGijlJ-tG4vxSyC8IKy7x09k5whGWMTx_ssIDLQlnAjW91JibhKvgSZnWvyNmFnWey_D6gdSF8ig"
      responses:
        '204':
          description: "OK"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /registration/code:
    post:
      summary: Запрос повторной отправки пользователю кода подтверждения
      operationId: requestRegistrationCode
      tags:
        - Registration
      requestBody:
        description: Почта или номер телефона пользователя
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordCodeRequest'
            examples:
              Email:
                value:
                  grantType: "email"
                  email: "test@gmail.com"
              PhoneNumber:
                value:
                  grantType: "phoneNumber"
                  phoneNumber: "+74951239999"
      responses:
        '202':
          description: "OK"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /registration/code/verify:
    post:
      summary: Отправка кода подтверждения
      operationId: verifyRegistrationCode
      tags:
        - Registration
      requestBody:
        description: Код подтверждения
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeRequest'
            examples:
              Email:
                value:
                  grantType: "email"
                  email: "test@gmail.com"
                  code: "123765"
              PhoneNumber:
                value:
                  grantType: "phoneNumber"
                  phoneNumber: "+74951239999"
                  code: "123765"
      responses:
        '200':
          description: Данные аккаунта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenData'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /account/password/code:
    post:
      summary: Запрос кода подтверждения
      operationId: getResetPasswordCode
      tags:
        - Account
      requestBody:
        description: Почта или номер телефона пользователя
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordCodeRequest'
            examples:
              Email:
                value:
                  grantType: "email"
                  email: "test@gmail.com"
              PhoneNumber:
                value:
                  grantType: "phoneNumber"
                  phoneNumber: "+74951239999"
      responses:
        '200':
          description: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /account/password/code/verify:
    post:
      summary: Отправка кода подтверждения
      operationId: verifyResetPasswordCode
      tags:
        - Account
      requestBody:
        description: Код подтверждения
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeRequest'
            examples:
              Email:
                value:
                  grantType: "email"
                  email: "test@gmail.com"
                  code: "12345121Yahct3"
              PhoneNumber:
                value:
                  grantType: "phoneNumber"
                  phoneNumber: "+74951239999"
                  code: "12345121Yahct3"
      responses:
        '204':
          description: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /account/password/reset:
    post:
      summary: Сброс пароля пользователя
      operationId: resetPassword
      tags:
        - Account
      requestBody:
        description: Данные для сброса пароля
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
            examples:
              Email:
                value:
                  grantType: "email"
                  email: "test@gmail.com"
                  password: "bc7$etyZ"
                  code: "12345121Yahct3"
              PhoneNumber:
                value:
                  grantType: "phoneNumber"
                  phoneNumber: "+74951239999"
                  password: "bc7$etyZ"
                  code: "12345121Yahct3"
      responses:
        '200':
          description: Данные аккаунта
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /account/user/update:
    put:
      summary: Обновление информации о пользователе
      operationId: updateUser
      tags:
        - Account
      security:
        - oAuth: []
      requestBody:
        description: Информация о пользователе
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /account/user:
    get:
      summary: Получение информации о пользователе
      operationId: getUser
      tags:
        - Account
      security:
        - oAuth: []
      responses:
        '200':
          description: "Информация о пользователе"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Auth:
      type: object
      required:
        - grantType
      properties:
        grantType:
          type: string
          description: "Тип авторизационных данных"
          enum:
            - email
            - phoneNumber
            - googleIdToken
            - appleIdToken
        idToken:
          type: string
          description: "Идентификационный токен от провайдера"
        phoneNumber:
          type: string
          description: "Номер телефона пользователя"
        email:
          type: string
          description: "Email пользователя"
        password:
          type: string
          description: "Пароль пользователя"

    Account:
      type: object
      properties:
        user:
          type: object
          $ref: '#/components/schemas/User'
        tokenData:
          type: object
          $ref: '#/components/schemas/TokenData'

    TokenData:
      type: object
      required:
        - accessToken
        - expiresIn
        - refreshToken
      properties:
        accessToken:
          type: string
        expiresIn:
          type: integer
          format: int64
        refreshToken:
          type: string

    User:
      type: object
      required:
        - firstName
        - lastName
        - gender
        - birthDate
        - country
        - city
        - contactPhoneNumber
        - education
        - maritalStatus
        - haveСhildren
        - badHabits
        - interests
      properties:
        firstName:
          type: string
        lastName:
          type: string
        photos:
          description: "Массив ссылок на фотограйии пользователя. Первая ссылка - основное фото пользователя."
          type: array
          items:
            type: string
            format: uri
        gender:
          type: string
          enum:
            - male
            - female
        birthDate:
          type: string
          format: data-time
          default: "24-09-2021"
        country:
          type: string
        city:
          type: string
        contactPhoneNumber:
          type: string
        education:
          description: "Уровень образования. Может принимать следущие значения: основное общее / basic general, среднее общее / secondary general, среднее профессиональное / secondary vocational, высшее (бакалавр, специалист) / higher (bachelor, specialist), высшее (магистр) / higher (мaster), учёная степень / academic degree"
          type: string
          enum:
            - basicGeneral
            - secondaryGeneral
            - secondaryVocational
            - higherBachelorOrSpecialist
            - higherMaster
            - academicDegree
        placeOfStudy:
          type: string
        placeOfWork:
          type: string
        workPosition:
          type: string
        maritalStatus:
          type: string
          enum:
            - notMarried
            - married
            - divorced
        haveСhildren:
          type: boolean
        badHabits:
          type: array
          items:
            type: string
            $ref: '#/components/schemas/BadHabit'
        interests:
          type: array
          items:
            type: string
        about:
          type: string


    CodeRequest:
      type: object
      required:
        - grantType
        - code
      properties:
        grantType:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        code:
          type: string

    ResetPasswordRequest:
      type: object
      required:
        - grantType
        - password
        - code
      properties:
        grantType:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        password:
          type: string
        code:
          type: string

    ResetPasswordCodeRequest:
      type: object
      required:
        - grantType
      properties:
        grantType:
          type: string
        email:
          type: string
        phoneNumber:
          type: string

    BadHabit:
      type: string
      enum:
        - smoking
        - alcohol
        - gambling
        - other

    Error:
      type: object
      required:
        - code
        - title
        - detail
      properties:
        code:
          type: integer
          format: int32
        title:
          type: string
        detail:
          type: string

  securitySchemes:
    oAuth:
      type: oauth2
      flows:
        password:
          tokenUrl: /login
          scopes: {}
