openapi: 3.0.0
info:
  title: Nikah Time
  version: 0.1.1
servers:
- url: https://virtserver.swaggerhub.com/cherryVsV/NikahTime/0.1.1
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
